### ISSUE TITLE
Hyphenation control

### ISSUE THREAD

**Issue by pbstudent** [pressbooks/ideas#363] opened 2021-03-19 11:17 UTC
### Feature Description
Enable or Disable Hyphenation for Web and eBook

### Feature Use Case

CSS does not always work for a particular book site. Need to have greater control of hyphenation in Theme Options - web  and ebook

### Other Notes
Sometimes the CSS for hyphens: none works but not consistently for all book sites as per https://pressbooks.community/t/how-do-you-stop-hyphenation-in-all-styles/632

**Comment by SteelWagstaff** [comment] 2021-06-06 00:51
@pbstudent I'm not aware of any way to control hyphenation in webbooks besides CSS, so not sure how a theme option would make much of a difference here, to be honest. See https://medium.com/clear-left-thinking/all-you-need-to-know-about-hyphenation-in-css-2baee2d89179 + https://css-tricks.com/almanac/properties/h/hyphenate/ + https://developer.mozilla.org/en-US/docs/Web/CSS/hyphens + https://caniuse.com/css-hyphens.

Can you provide an example of a book where you're having trouble getting hyphenation to display as intended (url and screenshot would be nice), a short description of what you think should be happening vs what is happening, and information about the operating system/browser combinations you're experiencing problems?

**Comment by pbstudent** [comment] 2021-06-06 08:59
Already tried CSS
`.textbox p, .part p, .chapter p, .back-matter p, body#tinymce.wp-editor p {
  hyphens: none;
}`

but the web version continues to display:
![Screenshot 2021-06-06 at 10-56-01 Acknowledgements – Exploration of an Online Open e-Textbook Publishing System Policy and ](https://user-images.githubusercontent.com/24277755/120918729-2e6a5480-c6b6-11eb-8f86-6444a1f6a6f7.png)

**Comment by SteelWagstaff** [comment] 2021-06-06 18:44
@pbstudent 
> **Can you provide an example of a book where you're having trouble** getting hyphenation to display as intended (**url** and screenshot would be nice), a short description of what you think should be happening vs what is happening, **and information about the operating system/browser combinations you're experiencing problems**?

**Comment by SteelWagstaff** [comment] 2021-09-09 02:36
@pbstudent, please see and reply to questions in previous comment so that we can attempt to reproduce the problem you’re encountering

**Comment by pbstudent** [comment] 2021-09-09 20:09
Example

https://mem-mem.com/research/front-matter/preface/

Would love to get rid of hyphenation.

**Comment by SteelWagstaff** [comment] 2021-09-20 14:36
@pbstudent when I visit that URL I see an account/host suspended message: 
![Screenshot from 2021-09-20 07-35-50.png](https://images.zenhubusercontent.com/6012398f80b7cb0f8d1385bc/53c8fae0-ed92-4ccc-a0c3-86e452a6c077)

**Comment by pbstudent** [comment] 2021-09-20 14:45
Hi,

Try the new change as of now: https://mem.on-linelearning.ca/research/front-matter/acknowledgements/

Thanks,
s.

**Comment by SteelWagstaff** [comment] 2021-09-21 23:23
@pbstudent I cloned the book and added 
```
.front-matter p, .part p, .chapter p, .back-matter p, body#tinymce.wp-editor p {
  hyphens: none;
  -webkit-hyphens: none;
}
```
to custom styles. The webbook no longer displays hyphens within paragraph content in all the browsers I tested (Chrome, Firefox, Safari, Edge, Opera, and Brave). You can check and confirm for yourself at https://integrations.pressbooks.network/hyphentest/front-matter/acknowledgements/ if you like. As there is a working method to remove hyphenation with Custom CSS, I'm going to close this issue.

**Closed as completed by SteelWagstaff** 2021-09-21 23:23 UTC
Labels: needs-reproduction

**Comment by pbstudent** [comment] 2021-09-22 07:22
Thank you Steel,

I had the same CSS except for one missing key element that resolved the issue:  .front-matter p, 

I would consider your "no hyphens" CSS snippet solution to be very important:

> .front-matter p, .part p, .chapter p, .back-matter p, body#tinymce.wp-editor p {
>   hyphens: none;
>   -webkit-hyphens: none;
> }

Sincerely,
Steve
