### ISSUE TITLE
Add plugin for broken link checking

### ISSUE THREAD

**Issue by weevie833** [pressbooks/ideas#298] opened 2020-04-13 13:58 UTC
### Feature Description

A dashboard element would show admins a running list of broken links as they are discovered.

### Feature Use Case

Faculty are currently tasked with manually checking all of the external links in their e-book prior to each term (and even during). Having a plugin aggregate potential dead links in one location would streamline this process. 

### Other Notes

The current WP plugin for this task [ https://wordpress.org/plugins/broken-link-checker/ ] has mixed reviews - some indicating curiously increased server CPU load. Not sure if these issues are related to this plugin, but worth testing if this feature request is enabled.

**Comment by colomet** [comment] 2020-04-13 18:23
I like to use as plugins applications with hight CPU use, so I could activate and deactivate just when they are required.

**Comment by SteelWagstaff** [comment] 2020-04-30 00:57
Hi all, see https://github.com/pressbooks/ideas/issues/298 for previous issue on this topic. I'm going to close this issue as a duplicate of that previous ticket and move conversation there.

**Closed as completed** 2020-04-30 00:59 UTC
