### ISSUE TITLE
next section new name

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#61] opened 2018-03-29 07:25 UTC
### Feature Scope

- [ ] Accessibility and inclusivity
- [ ] User interface (content creation)
- [ ] User interface (network home page & catalog)
- [ ] User interface (reading)
- [ ] Import/export formats
- [ ] Authoring tools
- [X] Book themes
- [ ] Integration with third-party services

### Feature Description

If we have chapters, why previous and next section is not previous and next chapter?

(and maybe it would be good for some situations if the administrators can choose between that sentence or the chapter name instead of next chapter or section #6)

### Feature Use Case

The same name in both places

### Other Notes

![captura de pantalla 2018-03-29 a las 9 22 47](https://user-images.githubusercontent.com/3929177/38075590-2321332e-3333-11e8-8eca-ae88673e748f.png)

**Comment by greatislander** [comment] 2018-03-29 11:35
Hey @colomet, you've opened a duplicate of your own issue: #6. Please don't do that.

**Closed by greatislander** 2018-03-29 11:35 UTC
