### ISSUE TITLE
Dinamic print books

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#338] opened 2020-09-24 16:45 UTC
### Feature Description

to have a QR code in the footer of each page with the print pdf version of a book

### Feature Use Case

if we print a page, the users can later to find the online version of the page where they can see the videos or play the exercises without writing by hand the page URL

### Other Notes

https://es.wordpress.org/plugins/dynamic-qr-code-generator/
https://es.wordpress.org/plugins/wp-qr-code-auto-generator/

**Comment by colomet** [comment] 2020-09-24 16:49
also, now, instead of multimedia content, we have the url of the dinamic content

![Screen-Shot-2018-03-10-at-6 07 00-PM](https://user-images.githubusercontent.com/3929177/94175309-cad92780-fe96-11ea-9eae-5539527b0e7c.png)


why not a QR instead? or both, so people do not require to write the page url by hand.

**Comment by colomet** [comment] 2020-09-27 08:30
something like:
![Screen Shot 2014-07-23 at 12 58 12 PM](https://user-images.githubusercontent.com/3929177/94360307-858e4300-00ac-11eb-8496-1fdd0340c8c3.png)

**Comment by beckej13820** [comment] 2021-03-24 23:27
Similar to this previous idea:

https://github.com/pressbooks/ideas/issues/69

**Comment by SteelWagstaff** [comment] 2021-06-06 00:34
Closing as duplicate of #69

**Closed as completed by SteelWagstaff** 2021-06-06 00:34 UTC
