### ISSUE TITLE
ADA compliant

### ISSUE THREAD

**Issue by colomet** [pressbooks/ideas#309] opened 2020-05-02 09:54 UTC
### Feature Description

is the web site ADA compliant? 
https://medium.com/@krisrivenburgh/the-ada-checklist-website-compliance-guidelines-for-2019-in-plain-english-123c1d58fad9

### Feature Use Case

To follow the Americans with Disabilities Act (ADA)

### Other Notes

We did try several plugins, and that´s the one we like the most (because of the simplicity)
WordPress.org

Accessible Poetry – WordPress Accessibility Plugin
https://wordpress.org/plugins/accessible-poetry/

WordPress Accessibility Plugin that provide solutions to common accessibility issues in websites. can help you keep your website more in line with the …

It have 70kb and 4 hits but we are thiking in an activation just for registered users.

Maybe it can be integrated with PB in a deeper level.

**Comment by SteelWagstaff** [comment] 2021-06-06 00:09
Closing as duplicate of https://github.com/pressbooks/pressbooks/issues/3645. Will add your recommendation for https://wordpress.org/plugins/accessible-poetry/ to that ticket

**Closed as completed by SteelWagstaff** 2021-06-06 00:09 UTC
Labels: a11y
