### ISSUE TITLE
Delete multiple chapters simultaneously

### ISSUE THREAD

**Issue by PressbooksLiz** [pressbooks/ideas#264] opened 2020-01-03 19:03 UTC
### Feature Description

I'd love to be select and trash multiple chapters at once.

### Feature Use Case

For instance if I imported a bunch of chapters from a doc by mistake in a book shell I want to keep.

**Comment by SteelWagstaff** [comment] 2020-01-03 19:14
Closed -- duplicate of #107

**Closed as completed by SteelWagstaff** 2020-01-03 19:14 UTC
