### ISSUE TITLE
Include screenshot for H5P activities in PDF/ePUB exports

### ISSUE THREAD

**Issue by pb-amy** [pressbooks/ideas#347] opened 2020-12-15 17:33 UTC
### Feature Description

Related to this issue: https://github.com/pressbooks/ideas/issues/263 - which had suggested printing static H5P activities in PDF/ePUB for practice purposes.

### Feature Use Case

It will provide context for H5P activities (what does it look like? what kind of questions? what activity type?) as right now, the PDF and ePUBs have no context for what kind of non-static activity is in it. Will definitely support accessibility needs and exports will be positively affected ubiquitously.

### Other Notes

It was mentioned in this client thread: https://pressbooks.zendesk.com/agent/tickets/3206. It is similar to another [idea](https://github.com/pressbooks/ideas/issues/263) as stated above; please merge if warranted.

**Comment by SteelWagstaff** [comment] 2021-06-06 00:38
Closing as duplicate of #263

**Closed as completed by SteelWagstaff** 2021-06-06 00:38 UTC
