### ISSUE TITLE
Footnotes in figure captions

### ISSUE THREAD

**Issue by jkeohane** [pressbooks/ideas#422] opened 2022-06-07 16:40 UTC
### Feature Description

The [footnote] tags do not work within figure captions, so I cannot attribute my figure via footnote.

### Feature Use Case

Anybody who includes a figure that need attributing, and wants to do this using a footnote.

### Other Notes

It should be an easy fix.

**Comment by SteelWagstaff** [comment] 2022-06-07 18:37
Closing as duplicate of https://github.com/pressbooks/ideas/issues/159

**Closed as completed by SteelWagstaff** 2022-06-07 18:37 UTC

**Comment by SteelWagstaff** [comment] 2022-06-07 18:39
@jkeohane the issue here has to do with shortcodes within shortcodes. It's technically possible to do this in WordPress, and is fairly straightforward for the webbook. It gets a bit complicated in the case of PDF footnotes, because we have to process/place them using some positioning magic when we generate PDFs. We'd like to add support for this, if possible, but don't know when we'll get to it. Still needs a bit more research, and isn't at the top of our priorities right now.
