### ISSUE TITLE
Facilitate metadata export from Pressbooks in a form suitable for XML upload to CrossRef for DOI registration

### ISSUE THREAD

**Issue by figaroblue32** [pressbooks/ideas#424] opened 2022-07-28 15:06 UTC
Digital Object Identifiers (DOIs) are persistent identifiers [PIDs] used to identify unique online resources. DOIs are commonly assigned to scholarly journal articles, acting both as a PID and a means for authors to track their individual usage and dissemination. 
Chapter-level DOIs are increasingly requested by academic authors.
The PressBooks platform offers a chapter-level DOI field. 
However, the background functionality to export the resulting metadata from PressBooks in a form compatible with CrossRef XML upload requirements for DOI registration does not currently exist. 

Feature use case
CrossRef is the leading DOI registration agency. Adding a metadata CrossRef XML export function would be attractive to the majority of PressBooks clients at educational institutions with the same use-case as ours.

Currently the only option is to manually enter the metadata and DOIs using CrossRef’s web deposit form: https://www.crossref.org/documentation/content-registration/web-deposit-form

This is feasible for single book-level DOIs, but not in the volume required by chapter-level DOIs, where it is too time-consuming.

CrossRef also allows direct upload of XML, which would be far preferable. 

Could developers add a metadata export option to PressBooks conforming to their XML schema as below?
https://data.crossref.org/reports/help/schema_doc/5.3.1/index.html

Our in-house IT person has successfully extracted required metadata [for a book with over 100 DOIs] from the exported PressBooks XHTML file, using a Python script. The resultant file was tested against CrossRef's parser test page, which reported it was valid for upload to CrossRef. This was then uploaded. All DOIs were successfully registered and now resolve.  
We are very happy to share approach and code to help build an official PressBooks export file.

**Comment by SteelWagstaff** [comment] 2022-07-29 16:16
Thanks for suggesting @figaroblue32 -- going to close this as a duplicate of #423 -- we would be interested to see the python script/method used by your colleague, however!

**Closed as completed by SteelWagstaff** 2022-07-29 16:16 UTC

**Comment by figaroblue32** [comment] 2022-08-01 11:50
Hi Steel,

Thanks for letting me know.

However, the reason I raised this as a new and separate issue was because the issue as you raised it is misleading, as it does not have a title that reflects the developmental request  – ‘Facilitate easy creation of DOIs for books and chapters with Crossref’ doesn’t really make any sense. The creation of DOIs is super easy, you need to be a registered institution with CrossRef  - the issue is PressBooks doesn’t support export of metadata for CrossRef.

Therefore, anyone searching for the same particular issue we are looking to have resolved would ignore/not click on the issue as it is currently described (whereas the query I raised elsewhere in the forum has had a comment from someone interested in the outcome, who as a result may look in the issues raised to follow updates).

Please could you either change #423 to reflect my issue, or delete #423 and re-post mine?

Then anyone potentially interested in the script can find it.

Tim says he had envisaged his code as half of the end solution: a homespun way to get the data followed by a solid method to write it out to XML. With more time, and a book that was already public, he would like to replace the first bit of the script with some API calls. That might make it better for other sites as well as us.

Please let me know when the issue has been updated so it reflects the request to ‘Facilitate metadata export from Pressbooks in a form suitable for XML upload to CrossRef for DOI registration’.

Many thanks in advance,

Catrina

**Comment by SteelWagstaff** [comment] 2022-08-01 14:13
@figaroblue32 i've renamed #423: "Produce Crossref-compatible XML metadata exports to make DOI creation faster" -- hope that better meets your desires/needs?

**Comment by figaroblue32** [comment] 2022-08-01 14:18
HI Steel

Could you change ‘creation’ to ‘registration of DOIs’ in the title and the body?

‘Creation’ is misleading, users will already have the DOIs.

Thanks, Catrina

**Comment by SteelWagstaff** [comment] 2022-08-01 14:36
Done!

*Steel Wagstaff*
Product Manager, Pressbooks
***@***.***

**Comment by figaroblue32** [comment] 2022-08-01 15:35
Brilliant, thanks!
